-- Create Database Actividad_1_1_2024
-- Go
-- Use Actividad_1_1_2024
-- Go
-- Create table Curso (
-- IDCURSO INT NOT NULL,
-- IDCATEGORIA INT NOT NULL,
-- NOMBRE VARCHAR(50) NULL,
-- IDIDIOMA INT NOT NULL,

-- )
-- GO
-- CREATE TABLE IDIOMA (
-- IDIDIOMA INT NOT NULL PRIMARY KEY, 
-- IDIOMA VARCHAR(50) NOT NULL UNIQUE,
-- )
-- GO
-- CREATE TABLE CURSOXCATEGORIA(
--     IDCURSO INT NOT NULL, 
--     IDCATEGORIA INT NOT NULL,
-- )
-- GO
-- CREATE TABLE CATEGORIA(
-- IDCATEGORIA INT NOT NULL PRIMARY KEY,
-- NIVEL VARCHAR(50) NOT NULL UNIQUE, 

-- )
-- GO 
-- CREATE TABLE CLASE (
--     IDCURSO INT NOT NULL,
--     IDCLASE INT NOT NULL PRIMARY KEY, 
--     NOMBRE VARCHAR(50) NOT NULL, 
-- )
-- GO 
-- CREATE TABLE CONTENIDO(
-- IDCLASE INT NOT NULL, 
-- IDCONTENIDO INT NOT NULL PRIMARY KEY, 
-- TEMA VARCHAR(50) NOT NULL, 

-- )
-- GO 
-- CREATE TABLE TIPOCONTENIDO
-- (
-- IDCONTENIDO INT NOT NULL, 
-- IDTIPOCONTENIDO INT NOT NULL PRIMARY KEY,

-- )

-- USE Actividad_1_1_2024

-- ALTER TABLE CURSO 
-- ADD CONSTRAINT FK_CURS FOREIGN KEY (IDIDIOMA) REFERENCES IDIOMA (IDIDIOMA) 

-- CREATE DATABASE Actividad_1_2_2024
-- GO
-- USE Actividad_1_2_2024
-- GO
-- CREATE TABLE USUARIO 
-- (
--     IDUSUARIO INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--     IDCURSO INT NOT NULL,
--     PROFESOR TINYINT NOT NULL,
-- )
-- GO
-- CREATE TABLE PAGOS 
-- (
-- IDPAGOS INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- IDUSUARIO INT NOT NULL FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
-- MONTO MONEY NULL,
-- FECHA DATETIME NOT NULL,
-- IDCURSO INT NOT NULL,
-- ESTADO TINYINT NOT NULL,

-- )
-- GO 
-- CREATE TABLE INSCRIPCION 
-- (
-- IDINSCRIPCION INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- IDPAGO INT NOT NULL FOREIGN KEY (IDPAGO) REFERENCES PAGOS (IDPAGOS),
-- CERTIFICACION TINYINT NOT NULL, 
-- RESENIA VARCHAR (500) NULL, 

-- )
-- CREATE TABLE DATOS_USUARIO
-- (
--     IDUSUARIO INT NOT NULL UNIQUE FOREIGN KEY (IDUSUARIO) REFERENCES USUARIO (IDUSUARIO),
--     NOMBRES VARCHAR (50) NOT NULL, 
--     APELLIDOS VARCHAR (50) NOT NULL, 
--     FECHA_NAC DATETIME NULL, 
--     EMAIL VARCHAR (50) NULL, 
--     IDDIRECCION INT NOT NULL, 
-- )
-- CREATE TABLE DIRECCION 
-- (
--     IDDIRECCION INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--     IDPAIS INT NOT NULL, 
--     IDPROVINCIA INT NOT NULL, 
--     LOCALIDAD VARCHAR (50) NULL, 

-- )
-- CREATE TABLE PAIS 
-- (
--     IDPAIS INT NOT NULL PRIMARY KEY IDENTITY (1,1),
--     NOMBRE VARCHAR NOT NULL, 
-- )
-- CREATE TABLE PROVINCIA 
-- (
-- IDPROVINCIA INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- IDPAIS INT NOT NULL FOREIGN KEY (IDPAIS) REFERENCES PAIS (IDPAIS),
-- NOMBRE VARCHAR(50) NOT NULL, 
-- )
-- ALTER TABLE DIRECCION 
-- ADD CONSTRAINT FK_IDPAIS FOREIGN KEY (IDPAIS) REFERENCES PAIS (IDPAIS)
-- ALTER TABLE DIRECCION 
-- ADD CONSTRAINT FK_IDPROVINCIA FOREIGN KEY (IDPROVINCIA) REFERENCES PROVINCIA (IDPROVINCIA)

-- ALTER TABLE DATOS_USUARIO 
-- ADD CONSTRAINT KF_IDDIRECCION FOREIGN KEY (IDDIRECCION) REFERENCES DIRECCION (IDDIRECCION)


-- USE Actividad_1_2_2024
-- GO 
-- CREATE TABLE CURSO 
-- (
-- IDCURSO INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- NOMBRE VARCHAR(50) NOT NULL, 
-- IDIDIOMA INT NOT NULL, 
-- COSTOCERT MONEY NOT NULL, 
-- COSTOCUR MONEY NOT NULL,    
-- IDNIVEL INT NOT NULL, 
-- FECHAESTRENO DATETIME NOT NULL,         
-- )
-- GO 
-- CREATE TABLE IDIOMA 
-- (
-- IDIDIOMA INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- NOMBRE VARCHAR(50) NOT NULL, 

-- )
-- ALTER TABLE CURSO
-- ADD CONSTRAINT FK_IDIOMA FOREIGN KEY (IDIDIOMA) REFERENCES IDIOMA (IDIDIOMA)
-- GO
-- CREATE TABLE NIVEL 
-- (
-- IDNIVEL INT NOT NULL PRIMARY KEY IDENTITY (1,1),
-- NOMBRE VARCHAR(50) NOT NULL 

-- )
-- ALTER TABLE CURSO 
-- ADD CONSTRAINT FK_IDNIVEL FOREIGN KEY (IDIDIOMA) REFERENCES NIVEL (IDNIVEL) 

-- INSERT INTO NIVEL (NOMBRE)
-- VALUES 
-- ('FACIL'),
-- ('INTERMEDIO'),
-- ('EXPERTO');

-- INSERT INTO IDIOMA (NOMBRE)
-- VALUES 
-- ('ESPAÑOL'),
-- ('INGLES'),
-- ('ALEMAN'),
-- ('PORTIGUES'),
-- ('FRANCES'),
-- ('ITALIANO');

-- INSERT INTO CURSO (NOMBRE, IDIDIOMA, COSTOCERT,COSTOCUR,IDNIVEL,FECHAESTRENO)
-- VALUES
-- ('PROGRAMACION', 1,14000,20000,2,'2024-04-10'),
-- ('INGLES',1,14000,20000,2,'2024-05-10'),
-- ('COCINA',2,10000,25000,2,'2024-05-10'),
-- ('LENGUA',1,5000,14000,2,'2024-05-09'),
-- ('MATEMATICAS',1,11000,14000,3,'2024-05-07'),
-- ('GEOGRAFIA',1,11000,18000,2,'2024-03-12'),
-- ('HISTORIA',1,9000,25000,1,'2024-04-11'),
-- ('ANALISIS DE DATOS',1,7000,24000,2,'2024-07-05'),
-- ('EXCEL',1,9000,23000,2,'2024-09-04'),
-- ('ALEMAN',1,6000,15000,3,'2024-02-04'),
-- ('CIENCIAS SOCIALES',1,4000,10000,2,'2024-03-03'),
-- ('JAVA',1,8000,12000,2,'2024-08-02'),
-- ('HTML',1,1000,11000,1,'2024-10-11');

-- ALTER TABLE PAIS
-- ALTER COLUMN NOMBRE VARCHAR(50) NOT NULL
-- INSERT INTO PAIS (NOMBRE)
-- VALUES
-- ('ARGERGENTINA'),
-- ('ESPANA'),
-- ('BRAZIL'),
-- ('ALEMANIA'),
-- ('PORTUGAL'),
-- ('URUGUAY');

ALTER TABLE USUARIO
ADD CONSTRAINT FK_CURSO FOREIGN KEY (IDCURSO) REFERENCES CURSO (IDCURSO)

INSERT INTO USUARIO (PROFESOR, IDCURSO)
VALUES 
(1,4),
(1,3),
(1,3),
(1,7),
(1,3),
(0,5),
(1,5),
(1,6),
(0,4),
(1,3),
(0,7),
(1,7),
(0,6);

-- INSERT INTO PROVINCIA (NOMBRE,IDPAIS)
-- VALUES
-- ('Buenos Aires',3),
-- ('Catamarca',3),
-- ('Chaco',3),
-- ('Chubut',3),
-- ('Córdoba',3),
-- ('Corrientes',3),
-- ('Entre Ríos',3),
-- ('Formosa',3),
-- ('Jujuy',3),
-- ('La Pampa',3),
-- ('La Rioja',3),
-- ('Mendoza',3),
-- ('Misiones',3),
-- ('Neuquén',3),
-- ('Río Negro',3),
-- ('Salta',3),
-- ('San Juan',3),
-- ('Tucumán',3),
-- ('San Luis',3),
-- ('Santa Cruz',3),
-- ('Santa Fe',3),
-- ('Santiago del Estero',3),
-- ('Tierra del Fuego',3);


